spring.application.name: commerce
spring.profiles.active: dev

spring:
  config:
    import:
      - classpath:config/db.yml
      - classpath:config/file.yml
      - classpath:config/logging.yml
      - classpath:config/web.yml
      - classpath:config/auth.yml
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:./docs/

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache.disabled: true
  swagger-ui:
    enabled: true
    url: /api/openapi3.yaml
    tags-sorter: alpha
    operations-sorter: alpha
    path: /swagger-ui.html
