spring.application.name: commerce
spring.profiles.active: dev

spring:
  config:
    import:
      - classpath:config/db.yml
      - classpath:config/file.yml
      - classpath:config/logging.yml
      - classpath:config/web.yml
      - classpath:config/secret/auth.yml
      - classpath:config/secret/db.yml
