package com.fastcampus.commerce.common.config

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@EnableConfigurationProperties
@Configuration
class ConfigurationPropertiesConfig
